pub const CONFIG: &str = "config";
pub const MARKET: &str = "market";
pub const POSITION: &str = "position";
pub const NFT: &str = "nft";
pub const NFT_COLLECTION: &str = "collection";
pub const POSITION_PAGE: &str = "pos_page";
pub const MPL_NOOP_ID: &str = "mnoopTCrg4p8ry25e4bcWA9XZjbNjMTfgYVGGEdRsf3";
pub const MPL_ACCOUNT_COMPRESSION_ID: &str = "mcmt6YrQEMKw8Mw43FmpRLmf7BqRnFMKmAcbxE3xkAW";
// pub const TREE: &str = "tree";
// pub const TREE_NAMESPACE_GLOBAL: &str = "global";
// pub const DEFAULT_TREE_MAX_DEPTH: u32 = 16; // 65,536 leaves
// pub const DEFAULT_TREE_MAX_BUFFER_SIZE: u32 = 64; // concurrency buffer
// pub const DEFAULT_TREE_PUBLIC: bool = true;
// pub const MAX_STALE_SLOTS: u64 = 150;
// pub const MIN_SAMPLES: u32 = 1;