pub const CONFIG: &str = "config";
pub const MARKET: &str = "market";
pub const POSITION_PAGE: &str = "pos_page";
pub const MARKET_CREATOR: &str = "market_creator";
pub const MPL_NOOP_ID: &str = "mnoopTCrg4p8ry25e4bcWA9XZjbNjMTfgYVGGEdRsf3";
pub const MPL_ACCOUNT_COMPRESSION_ID: &str = "mcmt6YrQEMKw8Mw43FmpRLmf7BqRnFMKmAcbxE3xkAW";
pub const BASE_URI: &str = "s3://depredict-metadata/";
pub const MAX_CREATOR_POSITIONS: u32 = 65_536;
pub const POSITIONS_PER_PAGE: u32 = super::state::trade::POSITION_PAGE_ENTRIES as u32;
// pub const MAX_POSITIONS_PER_PAGE: u8 = 16;
pub const FEE_BPS_DENOMINATOR: u16 = 10_000; // 100%
pub const MAX_FEE_AMOUNT: u16 = 200; // 2% - ludicrouslly high!

// pub const TREE: &str = "tree";
// pub const TREE_NAMESPACE_GLOBAL: &str = "global";
// pub const DEFAULT_TREE_MAX_DEPTH: u32 = 16; // 65,536 leaves
// pub const DEFAULT_TREE_MAX_BUFFER_SIZE: u32 = 64; // concurrency buffer
// pub const DEFAULT_TREE_PUBLIC: bool = true;
// pub const MAX_STALE_SLOTS: u64 = 150;
// pub const MIN_SAMPLES: u32 = 1;