[toolchain]
channel = "1.86.0"
package_manager = "yarn"
anchor_version = "0.31.1"
solana_version = "2.2.20"
solana_cli_version = "2.2.20"

[features]
resolution = true
skip-lint = false

[programs.localnet]
depredict = "DPxxBPxcgMwYuDDC8dbYZdqnGehErmwKQYC4ifVz5tpM"

[programs.devnet]
depredict = "DPxxBPxcgMwYuDDC8dbYZdqnGehErmwKQYC4ifVz5tpM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test-close-market = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/market/close-market.ts"
test-config = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/config.ts"
test-create-market = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/market/create-market.ts"
test-create-order = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/trade/create-order.ts"
test-create-sub-trade = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/user/create-subuser-trade.ts"
test-create-user = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/user/create-user.ts"
test-mint-pos = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/trade/mint-existing-position.ts"
test-order-flow = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/trade/order-flow.ts"
test-payout-nft = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/trade/payout-nft.ts"
test-resolve-market = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/market/resolve-market.ts"
test-update-market = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/market/update-market.ts"
test-user-trade = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/user/create-user-trade.ts"
test-payout-order = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/trade/payout-order.ts"
