[toolchain]
anchor_version = "0.31.1"
solana_version = "2.2.20"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
depredict = "deprZ6k7MU6w3REU6hJ2yCfnkbDvzUZaKE4Z4BuZBhU"

[programs.localnet]
depredict = "FMG8WchQ4AxEirv5nYcVeBoPQfgrwTBqhD2q7mGMvb33"

[programs.mainnet]
depredict = "deprZ6k7MU6w3REU6hJ2yCfnkbDvzUZaKE4Z4BuZBhU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test-all = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/run-all-tests.ts"
test-batch-open-claim = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/trade/batch-open-claim.ts"
test-check-config = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/check-config.ts"
test-claim-order = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/trade/claim-order.ts"
test-close-market = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/market/close-market.ts"
test-config = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/config.ts"
test-create-market = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/market/create-market.ts"
test-create-merkle-tree = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/create-merkle-tree.ts"
test-create-order = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/trade/create-order.ts"
test-create-usdc-mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/create-usdc-mint.ts"
test-market-creator = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/market/market-creator.ts"
test-pages = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/trade/test-pages.ts"
test-resolve-market = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/market/resolve-market.ts"
test-runner = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/run-all-tests.ts"
test-runner-continue = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/run-all-tests.ts -- --continue-on-failure"
test-setup-markets = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/setup-markets.ts"
test-update-market = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/market/update-market.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899
